### ISSUE TITLE
请问一下这个支持Objective-C吗

### ISSUE THREAD

**Issue by nanshanyi** [chriskempson/tomorrow-theme#316]
我用的Hexo的Next主题，但是我的代码块并没有彩色。

**Comment by macthecadillac** [comment]
Ma'am I don't think the majority of the people on GitHub could read Chinese.

**Comment by nanshanyi** [comment]
Excuse me, is this support Objective-C？I used the Next  theme in the Hexo, but my code block have  no color.

**Comment by macthecadillac** [comment]
I'm American but I can read Chinese just fine. The problem is,
      can the owner of the repository and the general public understand
      your comment/ticket? I suppose, since you opened a ticket, you
      would certainly want the problem fixed. To have the problem fixed,
      the dev has to be able to read your post so he/she could diagnose.
      Sending me the English translation without posting it in public
      wouldn't help one bit (as I said, I don't need it), unless you're
      only here to troll.
    
    
    On 06/30/2016 06:57 PM, 南山忆 wrote:
    
    
      Excuse me, is this support Objective-C？I used the Next theme in
        the Hexo, but my code block have no color.
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
