### ISSUE TITLE
Tomorrow themes not working on Atom 

### ISSUE THREAD

**Issue by michaelbasca** [chriskempson/tomorrow-theme#330]
They install correctly.  But when highlighting the Tomorrow theme option in Atom it reverts back to the original Atom Dark theme.

**Comment by cainster** [comment]
Unpacked folders into .atom/packages and able to select them in Settings, but reverts back to original Atom One Dark theme. Confirming that its still an issue 2 years later....

**Comment by michaelbasca** [comment]
2 years later.... it's been resolved.
