### ISSUE TITLE
Intellij Idea 2017.2.1 Tomorrow Dark is all broken

### ISSUE THREAD

**Issue by andreyorst** [chriskempson/tomorrow-theme#333]
Hello, thanks for a great theme, but in my Intellij Idea Community 2017.2.1 some color are just weird.
I've just imported settings from your `.jar` file and my code now look like this:
![image](https://user-images.githubusercontent.com/19470159/29117811-526ec8ee-7d08-11e7-8f6c-02033d10ffb2.png)
![image](https://user-images.githubusercontent.com/19470159/29117816-5845fce2-7d08-11e7-809b-7ff410f0bbc1.png)
And debug mode is _"awesome"_ too
![image](https://user-images.githubusercontent.com/19470159/29117831-6527be32-7d08-11e7-841d-c6cf46847843.png)
Is it a bug, or is it because Intellij changed something in theming and now theme is outdated?
Btw in VS Code (theme `Tomorrow and Tomorrow Night Theme Kit` from Microsoft) this code looks normal:
![image](https://user-images.githubusercontent.com/19470159/29119058-485fffb2-7d0d-11e7-8c2e-18ee9d225067.png)

**Comment by valix** [comment]
I found: http://www.phpstorm-themes.com/theme/boxytomorrow

**Comment by camsteffen** [comment]
Why is this closed?
